### ISSUE TITLE
Use gray95 for background color

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#55]
Make the color lighter to aid aesthetics

**Comment by sidd-2203** [comment]
The result ->
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/be3a89f5-074f-43ae-ba4c-4bf2126e3642)

**Comment by cannin** [comment]
@sidd-2203 it looks like this color gray is independent of the circle nodes. what happens with white instead of gray95?

**Comment by sidd-2203** [comment]
The problem is that the selector of the node is on all the nodes whose average value is NA not considering it is a Compound or a single node as shown below like the Cell Proliferation node and SFRP Compound both are turned white.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/db3b4621-7100-40ac-b887-f40102132321)

**Comment by sidd-2203** [comment]
Solved this problem by putting a selector on the PROCESS node and setting its color to grey,now rather than thinking of compound or complex or compartment we just colored every process with grey since its values also wont be present in the dataset so no conflict can be found.
Final Image of the pathway->
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/a9c58ad2-aa24-4490-98a6-da021343e0af)
